version: '3.8'

services:
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: pma
    restart: always
    environment:
      PMA_HOST: shuttle.proxy.rlwy.net        # Host จาก Railway
      PMA_PORT: 56195                         # Port จาก Railway
      PMA_USER: root                          # Username จาก Railway
      PMA_PASSWORD: ODkkOkzGVaawNrquGvBLQcJWKTPLAZTX   # Password จาก Railway
      PMA_ABSOLUTE_URI: http://localhost:8080/
      UPLOAD_LIMIT: 64M                       # อนุญาตให้อัปโหลดไฟล์ .sql ขนาดใหญ่
    ports:
      - "8080:80"                             # เปิด phpMyAdmin ที่ http://localhost:8080
    networks:
      - backend

networks:
  backend:
